[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "php82Extensions.pdo_mysql", "php82Extensions.mysqli"]

[start]
cmd = "php artisan migrate --force && php artisan db:seed --class=TestAccountsSeeder --force && php artisan serve --host=0.0.0.0 --port=${PORT:-8000}"
